name: Test
on:
  pull_request:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test_scala.yaml
        with: 
          workdir: news-sync